version: 2.1
orbs:
  welcome: circleci/welcome-orb@0.4.1
  
jobs:
    - build:
        - run: jupyter-nbconvert --execute ./Nearest_Neighbors_Classification.ipynb
        - store_artifacts:
            path: ./Nearest_Neighbors_Classification.html
      
      
      