version: 2.1

jobs:
    build:
        docker:
            - image: circleci/python:3.6.4 
        steps:
            - checkout
            - run: jupyter-nbconvert --execute ./Nearest_Neighbors_Classification.ipynb
            - store_artifacts:
                path: ./Nearest_Neighbors_Classification.html
      
      
      