version: 2.1

jobs:
    build:
        docker:
            - image: circleci/python:3.6.4 
        steps:
            - checkout
            - run: sudo pip install -r requirements.txt
            - run: sudo titanic/dataset_download.bash
            - run: jupyter-nbconvert --execute ./Nearest_Neighbors_Classification.ipynb
            - run: sudo titanic/submit_result.bash
            - store_artifacts:
                path: ./Nearest_Neighbors_Classification.html
      
      
      